application: basbrun
version: 1
runtime: python
api_version: 1

handlers:
 
- url: /images/(.*\.(gif|png|jpg))
  static_files: static/images/\1
  upload: static/images/(.*\.(gif|png|jpg))

- url: /basbrun.css
  static_files: static/basbrun.css
  upload: static/basbrun.css

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /.*
  script: main.py